# Generated by Django 6.0.4 on 2026-05-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='heroes/', verbose_name='Image')),
                ('gender', models.CharField(max_length=8, verbose_name='Gender')),
                ('species', models.JSONField(verbose_name='Species')),
                ('position', models.JSONField(verbose_name='Role')),
                ('attribute', models.CharField(max_length=16, verbose_name='Attribute')),
                ('attack_type', models.CharField(max_length=8, verbose_name='Attack Type')),
                ('complexity', models.CharField(max_length=8, verbose_name='Complexity')),
                ('date', models.PositiveSmallIntegerField(verbose_name='Release Year')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png_file', models.FileField(max_length=256, upload_to='', verbose_name='Ability image')),
                ('text', models.CharField(max_length=128, verbose_name='Ability name')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hero', verbose_name='Hero')),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='LoadScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_screen', models.ImageField(blank=True, null=True, upload_to='loading_screens/', verbose_name='Loading screen')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hero', verbose_name='Hero')),
            ],
            options={
                'verbose_name': 'Loading screen',
                'verbose_name_plural': 'Loading screens',
            },
        ),
        migrations.CreateModel(
            name='VoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(blank=True, max_length=256, null=True, upload_to='voice_lines/', verbose_name='Voice phrase')),
                ('text', models.CharField(max_length=256, verbose_name='Text phrase')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hero', verbose_name='Hero')),
            ],
            options={
                'verbose_name': 'Voice phrase',
                'verbose_name_plural': 'Voice phrases',
            },
        ),
    ]
